### ISSUE TITLE
network data

### ISSUE THREAD

**Issue by wxlpp** [Ramotion/gliding-collection#1]
Whether it supports network data loading？

**Comment by av0c0der** [comment]
You need to load your data as usual, only data binding will change a little. See demo project on how to deal with different sections.

**Comment by wxlpp** [comment]
but my section title is network data too，
I added the function and modified setupVerticalStack () to remove the previously added button
Is currently valid
```swift
 func reloadTitle() {
        setupVerticalStack()
        setNeedsLayout()
    }```

**Comment by av0c0der** [comment]
@wxlpp ok. Just pushed version `1.0.1` and now `GlidingCollection` have `reloadData` method which does actually what you need. Just make sure that your datasource is up to date!
