### ISSUE TITLE
Broken Horizontal Sliding When Card Size Change

### ISSUE THREAD

**Issue by danielchangsoojones** [Ramotion/gliding-collection#2]
If you change the card size to a smaller width, then when you scroll horizontally, it is not snapping to each cell like it normally does. It is like the snapping is still calculated upon the default height. I set my card size to: CGSize(width: 200, height: 280)

**Comment by av0c0der** [comment]
@danielchangsoojones please use `GlidingConfig` to customize appearance of this control. I'm just updated demo project and moved configuration to `AppDelegate`.

There are property named `cardsSize` so you need to set your custom size to this property:
```swift
config.cardsSize = CGSize(width: 200, height: 280)
```
