### ISSUE TITLE
Custom Category Header Views

### ISSUE THREAD

**Issue by danielchangsoojones** [Ramotion/gliding-collection#3]
Would it be possible to create custom category heard views? For example, I want to be able to have the "-Boots" label on the left side, and I would like to have an "more>" label on the right side. It could be done in a similar fashion as how UICollection's delegate allows you to return a view for a section header.

**Comment by av0c0der** [comment]
I can't say you that we'll implement this soon. Feel free to contribute and submit an PR! I'll close this for now.
