### ISSUE TITLE
Custom Cell Size Based On expandedItemIndex

### ISSUE THREAD

**Issue by YouKnowOJ** [Ramotion/gliding-collection#5]
Is it possible to change the cardSize based on the expandedItemIndex? 
I tried doing this by setting the cell frame based on the expandedItemIndex, but it distorts the collection cell view.

**Comment by av0c0der** [comment]
@YouKnowOJ sorry for the delay. Custom cell sizing not supported.

You need to disable parallax, shadow effect and set imageView's contentMode to `aspectFit`.
This way you can achieve desired effect.
